### ISSUE TITLE
Make log file relative to user

### ISSUE THREAD

**Issue by brendalf** [brendalf/workhours#3]
The file we save the log of actions should be relative to the user, otherwise it will create a new file in every folder we run the command.
[`click.get_app_dir`](https://click.palletsprojects.com/en/8.1.x/api/?highlight=open_file#click.get_app_dir) can probably help.

**Comment by brendalf** [comment]
We should also change the name of the file.
IMO, the default path should be: `~/.workhours/log.csv`.

**Comment by amferraboli** [comment]
Solved in MR #6 .
